name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop, release/*]

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        id: nvm
        run: echo "::set-output name=NODE_VERSION::$(cat .nvmrc)"

      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{runner.os}}-yarn-${{hashFiles('**/yarn.lock')}}
          restore-keys: |
            ${{runner.os}}-yarn-

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Format
        run: yarn prettier --check .

      - name: Typescript check
        run: yarn tsc

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test:coverage

      - name: Build
        run: yarn run build

      - name: Test Reporting
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./coverage/lcov.info

      - name: Add to codecov
        uses: codecov/codecov-action@v2

  deploy:
    name: Deploy
    needs: quality
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'complex-celery-github'
          heroku_email: 'michael2.gray@gmail.com'
